Testing out pytester-cov.

diff --git a/.github/workflows/coverage_python.yml b/.github/workflows/coverage_python.yml
--- a/.github/workflows/coverage_python.yml
+++ b/.github/workflows/coverage_python.yml
@@ -17,9 +17,25 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install -r ./python_code/requirements.txt
-    - name: Test with pytest
+    - name: pytest
+      id: pytest
+      uses: alexanderdamiani/pytester-cov@v1.0.1
+      with:
+        pytest-root-dir: './python_code/code'
+        cov-omit-list: 'test/*, temp/main3.py, temp/main4.py'
+        cov-threshold-single: 80
+        cov-threshold-total: 80
+    - name: Coverage single fail - exit
+      if: ${{ steps.pytest.outputs.cov-threshold-single-fail == 'true' }}
       run: |
-        pip install pytest pytest-cov
-        python -m pytest --cov=./python_code/code > pytest-coverage.txt
-    - name: Comment coverage
-      uses: coroo/pytest-coverage-commentator@v1.0.2
+        echo "cov single fail ${{ steps.pytest.outputs.cov-threshold-single-fail }}"
+        exit 1
+    - name: Coverage total fail - exit
+      if: ${{ steps.pytest.outputs.cov-threshold-total-fail == 'true' }}
+      run: |
+        echo "cov single fail ${{ steps.pytest.outputs.cov-threshold-total-fail }}"
+        exit 1
+    - name: Commit pytest coverage table
+      uses: peter-evans/commit-comment@v1
+      with:
+        body: ${{ steps.pytest.outputs.output-table }}
